# version: '3.9'

# services:
#   django:

#     build: .

#     container_name: django

#     #command: python manage.py runserver 0.0.0.0:8000
#     command: python try_for_freeipa.py
#     volumes:
#       - .:/usr/src/app

#     ports:
#       - 8000:8000

version: '3.9'

services:
  python-script:
    build: .
    container_name: python_script_runner
    volumes:
      - /opt/freeipa/data/etc/krb5.conf:/etc/krb5.conf